name: merge CI
on: [ pull-request ]
jobs:
 Explore-GitHub-Action:
  runs-on: [ ubuntu-latest, windows-latest ]
  steps:
   - uses: actions/checkout@v2
   - run: echo "the job was automatically triggered by a ${{ github.even_name }} event ."
   - run: python main.py

