name: merge CI
on: [ pull_request ]
jobs:
 Test:
  runs-on: ${{ matrix.oc }}
  strategy:
   matrix:
    os: [ macos-latest, ubuntu-latest, windows-latest ]
  steps:

   - uses: actions/checkout@v2 
   - run: python main.py

